project:
  type: website
  output-dir: docs

website:
  title: "Skye Goldson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
       -href: internship.qmd
        text: Interships
       -href: project.qmd
        text: Projects
      
format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

